# Generated by Django 6.0.4 on 2026-05-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_meallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Body weight in kg', max_digits=5, null=True),
        ),
    ]
